# Generated by Django 5.1.2 on 2025-12-27 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        ('equipment', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.department'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.maintenanceteam'),
        ),
    ]
